name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build & Test
      run: |
        npm i
        npm run build
        npm run test